#Do not edit this file it will get overwritten. Edit the org file instead else create a new python script.
from enum import Enum

import numpy as np
import cv2 as cv

class RGBColor(Enum):
    RED = (0, 0, 255)
    GREEN = (0, 255, 0)
    BLUE = (255, 0, 0)

class XHImage:
    def __init__(self, path):
        self.image = cv.imread(path)

    def getImage(self):
        return self.image

    def toGrayScale(self):
        return cv.cvtColor(self.image, cv.COLOR_BGR2GRAY)

#IndexOfContours defines the set of contours to be used.
#The value of -1 indicates the use of all contours.
def drawContours(imgPath: str, contourColor: RGBColor, threshold: int, indexOfContours: int = -1) -> None:

    img = XHImage(imgPath)

    ret, thresh = cv.threshold(img.toGrayScale(), threshold, 255, 0)
    contours, hierarchy = cv.findContours(thresh, cv.RETR_TREE, cv.CHAIN_APPROX_NONE)

    cv.drawContours(img.getImage(), contours, indexOfContours, contourColor.value, 2)

    cv.imshow("ContourDrawn", img.getImage())
    cv.waitKey(0)
    cv.destroyAllWindows()

drawContours("./images/batch1/13894.png", RGBColor.BLUE, 23)
